-- ============================================================================
-- SCRIPT: CLONAR TENANT (Schema) - BI SaaS
-- ============================================================================
--
-- VERSAO: 2.0 - Baseado na estrutura real do schema 'okilao'
-- DATA: Dezembro 2024
--
-- USO: Substitua as variaveis abaixo antes de executar:
--   - okilao = Schema de origem (ex: 'okilao')
--   - solpet = Schema de destino (ex: 'novo_cliente')
--   - solpet   = Nome do tenant (ex: 'Novo Cliente Ltda')
--
-- IMPORTANTE: Este script NAO copia dados, apenas estrutura!
-- Para copiar dados, execute as queries INSERT...SELECT no final.
--
-- ============================================================================

-- ============================================================================
-- VARIAVEIS (EDITE AQUI!)
-- ============================================================================
-- Execute no SQL Editor do Supabase com Find & Replace:
--   Substituir: okilao  ->  okilao
--   Substituir: solpet  ->  novo_cliente
--   Substituir: solpet    ->  Novo Cliente Ltda
-- ============================================================================

\echo '=============================================='
\echo 'INICIANDO CLONAGEM DE TENANT'
\echo 'Origem: okilao'
\echo 'Destino: solpet'
\echo '=============================================='

-- ============================================================================
-- PASSO 1: CRIAR SCHEMA
-- ============================================================================

DROP SCHEMA IF EXISTS solpet CASCADE;
CREATE SCHEMA solpet;

\echo '>> Schema solpet criado'

-- ============================================================================
-- PASSO 2: CRIAR TABELAS (Estrutura baseada no schema okilao)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 2.1 Tabela: departamentos_nivel1 (para hierarquia de despesas)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.departamentos_nivel1 (
  id BIGINT PRIMARY KEY,
  descricao TEXT
);

-- ----------------------------------------------------------------------------
-- 2.2 Tabela: departments (tabela legada, mantida para compatibilidade)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.departments (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT,
  code TEXT,
  name TEXT,
  level INTEGER
);

-- ----------------------------------------------------------------------------
-- 2.3 Tabelas: departments_level_1 ate level_6 (Hierarquia de produtos)
-- ----------------------------------------------------------------------------

-- Level 6 (mais alto da hierarquia)
CREATE TABLE solpet.departments_level_6 (
  departamento_id BIGINT PRIMARY KEY,
  descricao TEXT
);

-- Level 5
CREATE TABLE solpet.departments_level_5 (
  departamento_id BIGINT PRIMARY KEY,
  descricao TEXT,
  pai_level_6_id BIGINT REFERENCES solpet.departments_level_6(departamento_id)
);

-- Level 4
CREATE TABLE solpet.departments_level_4 (
  departamento_id BIGINT PRIMARY KEY,
  descricao TEXT,
  pai_level_5_id BIGINT REFERENCES solpet.departments_level_5(departamento_id),
  pai_level_6_id BIGINT REFERENCES solpet.departments_level_6(departamento_id)
);

-- Level 3
CREATE TABLE solpet.departments_level_3 (
  departamento_id BIGINT PRIMARY KEY,
  descricao TEXT,
  pai_level_4_id BIGINT REFERENCES solpet.departments_level_4(departamento_id),
  pai_level_5_id BIGINT REFERENCES solpet.departments_level_5(departamento_id),
  pai_level_6_id BIGINT REFERENCES solpet.departments_level_6(departamento_id)
);

-- Level 2
CREATE TABLE solpet.departments_level_2 (
  departamento_id BIGINT PRIMARY KEY,
  descricao TEXT,
  pai_level_3_id BIGINT REFERENCES solpet.departments_level_3(departamento_id),
  pai_level_4_id BIGINT REFERENCES solpet.departments_level_4(departamento_id),
  pai_level_5_id BIGINT REFERENCES solpet.departments_level_5(departamento_id),
  pai_level_6_id BIGINT REFERENCES solpet.departments_level_6(departamento_id)
);

-- Level 1 (mais baixo - onde os produtos estao vinculados)
CREATE TABLE solpet.departments_level_1 (
  departamento_id BIGINT PRIMARY KEY,
  descricao TEXT,
  pai_level_2_id BIGINT REFERENCES solpet.departments_level_2(departamento_id),
  pai_level_3_id BIGINT REFERENCES solpet.departments_level_3(departamento_id),
  pai_level_4_id BIGINT REFERENCES solpet.departments_level_4(departamento_id),
  pai_level_5_id BIGINT REFERENCES solpet.departments_level_5(departamento_id),
  pai_level_6_id BIGINT REFERENCES solpet.departments_level_6(departamento_id)
);

-- ----------------------------------------------------------------------------
-- 2.4 Tabela: descontos_venda
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.descontos_venda (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_desconto DATE,
  filial_id BIGINT,
  valor_desconto NUMERIC,
  produto_id BIGINT,
  quantidade NUMERIC
);

-- ----------------------------------------------------------------------------
-- 2.5 Tabela: despesas
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.despesas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_despesa BIGINT,
  data_despesa DATE,
  filial_id BIGINT,
  descricao_despesa TEXT,
  valor NUMERIC,
  numero_nota TEXT,
  serie_nota TEXT,
  usuario TEXT,
  observacao TEXT
);

-- ----------------------------------------------------------------------------
-- 2.6 Tabela: despesas_diarias_por_filial (agregacao de despesas)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.despesas_diarias_por_filial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL,
  filial_id BIGINT NOT NULL,
  total_despesas NUMERIC DEFAULT 0,
  UNIQUE (data, filial_id)
);

-- ----------------------------------------------------------------------------
-- 2.7 Tabela: entradas (notas de entrada)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.entradas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_entrada BIGINT,
  data_entrada DATE,
  filial_id BIGINT,
  transacao TEXT,
  valor_contabil NUMERIC,
  custo NUMERIC
);

-- ----------------------------------------------------------------------------
-- 2.8 Tabela: etl_controle (controle de ETL)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.etl_controle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabela TEXT NOT NULL,
  ultima_execucao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ultimo_id_processado BIGINT DEFAULT 0,
  registros_processados BIGINT DEFAULT 0,
  status TEXT DEFAULT 'pendente'::TEXT,
  UNIQUE (tabela)
);

-- ----------------------------------------------------------------------------
-- 2.9 Tabela: etl_execucoes (log de execucoes ETL)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.etl_execucoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabela TEXT NOT NULL,
  data_inicio TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  data_fim TIMESTAMP WITH TIME ZONE,
  registros_inseridos BIGINT DEFAULT 0,
  registros_atualizados BIGINT DEFAULT 0,
  registros_erro BIGINT DEFAULT 0,
  status TEXT DEFAULT 'em_andamento'::TEXT,
  mensagem_erro TEXT
);

-- ----------------------------------------------------------------------------
-- 2.10 Tabela: faturamento
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.faturamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_saida BIGINT,
  data_saida DATE,
  filial_id BIGINT,
  transacao TEXT,
  cancelado BOOLEAN DEFAULT FALSE,
  valor_contabil NUMERIC,
  custo_sem_icms NUMERIC
);

-- ----------------------------------------------------------------------------
-- 2.11 Tabela: filiais (NOTA: estrutura real nao encontrada no okilao)
-- Esta tabela e referenciada mas pode estar no schema public
-- ----------------------------------------------------------------------------
-- Se necessario, criar aqui a tabela filiais

-- ----------------------------------------------------------------------------
-- 2.12 Tabela: metas_mensais
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.metas_mensais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filial_id BIGINT NOT NULL,
  data DATE NOT NULL,
  dia_semana TEXT,
  meta_percentual NUMERIC,
  data_referencia DATE,
  valor_referencia NUMERIC,
  valor_meta NUMERIC,
  valor_realizado NUMERIC DEFAULT 0,
  diferenca NUMERIC DEFAULT 0,
  diferenca_percentual NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (filial_id, data)
);

-- ----------------------------------------------------------------------------
-- 2.13 Tabela: motivos_perda
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.motivos_perda (
  id BIGINT PRIMARY KEY,
  descricao TEXT
);

-- ----------------------------------------------------------------------------
-- 2.14 Tabela: perdas
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.perdas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id BIGINT,
  filial_id BIGINT,
  data_perda DATE,
  quantidade NUMERIC,
  valor_perda NUMERIC,
  motivo_id BIGINT REFERENCES solpet.motivos_perda(id)
);

-- ----------------------------------------------------------------------------
-- 2.15 Tabela: produtos
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.produtos (
  id BIGINT PRIMARY KEY,
  descricao TEXT,
  departamento_id BIGINT REFERENCES solpet.departments_level_1(departamento_id),
  unidade TEXT,
  preco_venda NUMERIC,
  custo NUMERIC,
  ativo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 2.16 Tabela: setores
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.setores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  nivel INTEGER DEFAULT 1,
  departamento_ids BIGINT[] DEFAULT '{}'::BIGINT[],
  ativo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 2.17 Tabela: metas_setor
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.metas_setor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setor_id BIGINT NOT NULL REFERENCES solpet.setores(id),
  filial_id BIGINT NOT NULL,
  data DATE NOT NULL,
  valor_meta NUMERIC DEFAULT 0,
  meta_percentual NUMERIC DEFAULT 0,
  valor_realizado NUMERIC DEFAULT 0,
  diferenca NUMERIC DEFAULT 0,
  diferenca_percentual NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (setor_id, filial_id, data)
);

-- ----------------------------------------------------------------------------
-- 2.18 Tabelas de staging (ETL)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.staging_departamentos (
  id BIGINT PRIMARY KEY,
  codigo_interno TEXT,
  descricao TEXT,
  nivel INTEGER,
  parent_id BIGINT,
  processado BOOLEAN DEFAULT FALSE,
  data_importacao TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE solpet.staging_produtos (
  id BIGINT PRIMARY KEY,
  codigo TEXT,
  descricao TEXT,
  departamento_id BIGINT,
  unidade TEXT,
  preco_venda NUMERIC,
  custo NUMERIC,
  ativo BOOLEAN,
  processado BOOLEAN DEFAULT FALSE,
  data_importacao TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 2.19 Tabela: tipos_despesa
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.tipos_despesa (
  id BIGINT PRIMARY KEY,
  descricao TEXT,
  departamentalizacao_nivel1 BIGINT REFERENCES solpet.departamentos_nivel1(id)
);

-- ----------------------------------------------------------------------------
-- 2.20 Tabela: vendas (principal - alto volume)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.vendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produto BIGINT REFERENCES solpet.produtos(id),
  data_venda DATE NOT NULL,
  filial_id BIGINT,
  quantidade NUMERIC,
  valor_vendas NUMERIC,
  valor_custo NUMERIC,
  desconto NUMERIC DEFAULT 0
);

-- ----------------------------------------------------------------------------
-- 2.21 Tabela: vendas_diarias_por_filial (agregacao)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.vendas_diarias_por_filial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL,
  filial_id BIGINT NOT NULL,
  total_vendas NUMERIC DEFAULT 0,
  total_custo NUMERIC DEFAULT 0,
  total_desconto NUMERIC DEFAULT 0,
  quantidade_itens NUMERIC DEFAULT 0,
  UNIQUE (data, filial_id)
);

-- ----------------------------------------------------------------------------
-- 2.22 Tabela: vendas_por_departamento (agregacao por departamento)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.vendas_por_departamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL,
  filial_id BIGINT NOT NULL,
  departamento_id BIGINT NOT NULL,
  total_vendas NUMERIC DEFAULT 0,
  total_custo NUMERIC DEFAULT 0,
  total_desconto NUMERIC DEFAULT 0,
  quantidade_itens NUMERIC DEFAULT 0,
  UNIQUE (data, filial_id, departamento_id)
);

-- ----------------------------------------------------------------------------
-- 2.23 Tabela: vendas_produto_mes (agregacao mensal por produto)
-- ----------------------------------------------------------------------------
CREATE TABLE solpet.vendas_produto_mes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano INTEGER NOT NULL,
  mes INTEGER NOT NULL,
  produto_id BIGINT NOT NULL,
  filial_id BIGINT NOT NULL,
  quantidade_total NUMERIC DEFAULT 0,
  valor_total NUMERIC DEFAULT 0,
  custo_total NUMERIC DEFAULT 0,
  desconto_total NUMERIC DEFAULT 0,
  UNIQUE (ano, mes, produto_id, filial_id)
);

\echo '>> Tabelas criadas'

-- ============================================================================
-- PASSO 3: CRIAR INDICES (baseado nos indices do okilao)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 3.1 Indices em vendas (CRITICOS para performance)
-- ----------------------------------------------------------------------------

-- Indice covering para queries de vendas por periodo
CREATE INDEX idx_solpet_vendas_data_covering
ON solpet.vendas(data_venda, filial_id, id_produto)
INCLUDE (valor_vendas)
WHERE data_venda >= '2024-01-01';

-- Indice para busca por filial e data
CREATE INDEX idx_solpet_vendas_filial_data
ON solpet.vendas(filial_id, data_venda);

-- Indice para busca por produto
CREATE INDEX idx_solpet_vendas_produto
ON solpet.vendas(id_produto);

-- Indice para agregacoes diarias
CREATE INDEX idx_solpet_vendas_data
ON solpet.vendas(data_venda);

-- Indice composto para relatorios
CREATE INDEX idx_solpet_vendas_data_filial_produto
ON solpet.vendas(data_venda, filial_id, id_produto);

-- ----------------------------------------------------------------------------
-- 3.2 Indices em departments_level_1
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_dept_l1_pai_level_2
ON solpet.departments_level_1(pai_level_2_id)
INCLUDE (departamento_id)
WHERE pai_level_2_id IS NOT NULL;

CREATE INDEX idx_solpet_dept_l1_pai_level_3
ON solpet.departments_level_1(pai_level_3_id)
INCLUDE (departamento_id)
WHERE pai_level_3_id IS NOT NULL;

CREATE INDEX idx_solpet_dept_l1_pai_level_4
ON solpet.departments_level_1(pai_level_4_id)
INCLUDE (departamento_id)
WHERE pai_level_4_id IS NOT NULL;

CREATE INDEX idx_solpet_dept_l1_pai_level_5
ON solpet.departments_level_1(pai_level_5_id)
INCLUDE (departamento_id)
WHERE pai_level_5_id IS NOT NULL;

CREATE INDEX idx_solpet_dept_l1_pai_level_6
ON solpet.departments_level_1(pai_level_6_id)
INCLUDE (departamento_id)
WHERE pai_level_6_id IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 3.3 Indices em outros niveis de departamento
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_dept_l2_pai_level_3
ON solpet.departments_level_2(pai_level_3_id);

CREATE INDEX idx_solpet_dept_l2_pai_level_4
ON solpet.departments_level_2(pai_level_4_id);

CREATE INDEX idx_solpet_dept_l2_pai_level_5
ON solpet.departments_level_2(pai_level_5_id);

CREATE INDEX idx_solpet_dept_l2_pai_level_6
ON solpet.departments_level_2(pai_level_6_id);

CREATE INDEX idx_solpet_dept_l3_pai_level_4
ON solpet.departments_level_3(pai_level_4_id);

CREATE INDEX idx_solpet_dept_l3_pai_level_5
ON solpet.departments_level_3(pai_level_5_id);

CREATE INDEX idx_solpet_dept_l3_pai_level_6
ON solpet.departments_level_3(pai_level_6_id);

CREATE INDEX idx_solpet_dept_l4_pai_level_5
ON solpet.departments_level_4(pai_level_5_id);

CREATE INDEX idx_solpet_dept_l4_pai_level_6
ON solpet.departments_level_4(pai_level_6_id);

CREATE INDEX idx_solpet_dept_l5_pai_level_6
ON solpet.departments_level_5(pai_level_6_id);

-- ----------------------------------------------------------------------------
-- 3.4 Indices em metas_setor
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_metas_setor_lookup
ON solpet.metas_setor(setor_id, filial_id, data);

CREATE INDEX idx_solpet_metas_setor_periodo
ON solpet.metas_setor(data, setor_id);

CREATE INDEX idx_solpet_metas_setor_filial
ON solpet.metas_setor(filial_id);

-- ----------------------------------------------------------------------------
-- 3.5 Indices em metas_mensais
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_metas_mensais_filial_data
ON solpet.metas_mensais(filial_id, data);

CREATE INDEX idx_solpet_metas_mensais_data
ON solpet.metas_mensais(data);

-- ----------------------------------------------------------------------------
-- 3.6 Indices em produtos
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_produtos_dept
ON solpet.produtos(departamento_id);

CREATE INDEX idx_solpet_produtos_ativo
ON solpet.produtos(ativo)
WHERE ativo = TRUE;

-- ----------------------------------------------------------------------------
-- 3.7 Indices em descontos_venda
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_descontos_data_filial
ON solpet.descontos_venda(data_desconto, filial_id);

CREATE INDEX idx_solpet_descontos_produto
ON solpet.descontos_venda(produto_id);

-- ----------------------------------------------------------------------------
-- 3.8 Indices em despesas
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_despesas_data_filial
ON solpet.despesas(data_despesa, filial_id);

CREATE INDEX idx_solpet_despesas_tipo
ON solpet.despesas(id_tipo_despesa);

CREATE INDEX idx_solpet_despesas_data
ON solpet.despesas(data_despesa);

-- ----------------------------------------------------------------------------
-- 3.9 Indices em perdas
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_perdas_data_filial
ON solpet.perdas(data_perda, filial_id);

CREATE INDEX idx_solpet_perdas_produto
ON solpet.perdas(produto_id);

CREATE INDEX idx_solpet_perdas_motivo
ON solpet.perdas(motivo_id);

-- ----------------------------------------------------------------------------
-- 3.10 Indices em faturamento
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_faturamento_data_filial
ON solpet.faturamento(data_saida, filial_id);

CREATE INDEX idx_solpet_faturamento_cancelado
ON solpet.faturamento(cancelado)
WHERE cancelado = FALSE;

-- ----------------------------------------------------------------------------
-- 3.11 Indices em entradas
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_entradas_data_filial
ON solpet.entradas(data_entrada, filial_id);

-- ----------------------------------------------------------------------------
-- 3.12 Indices em vendas_diarias_por_filial
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_vdf_data
ON solpet.vendas_diarias_por_filial(data);

CREATE INDEX idx_solpet_vdf_filial
ON solpet.vendas_diarias_por_filial(filial_id);

-- ----------------------------------------------------------------------------
-- 3.13 Indices em vendas_por_departamento
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_vpd_data_filial
ON solpet.vendas_por_departamento(data, filial_id);

CREATE INDEX idx_solpet_vpd_dept
ON solpet.vendas_por_departamento(departamento_id);

-- ----------------------------------------------------------------------------
-- 3.14 Indices em vendas_produto_mes
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_vpm_ano_mes
ON solpet.vendas_produto_mes(ano, mes);

CREATE INDEX idx_solpet_vpm_produto
ON solpet.vendas_produto_mes(produto_id);

CREATE INDEX idx_solpet_vpm_filial
ON solpet.vendas_produto_mes(filial_id);

-- ----------------------------------------------------------------------------
-- 3.15 Indices em tipos_despesa
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_tipos_despesa_nivel1
ON solpet.tipos_despesa(departamentalizacao_nivel1);

-- ----------------------------------------------------------------------------
-- 3.16 Indices em etl_controle
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_etl_controle_status
ON solpet.etl_controle(status);

-- ----------------------------------------------------------------------------
-- 3.17 Indices em setores
-- ----------------------------------------------------------------------------
CREATE INDEX idx_solpet_setores_ativo
ON solpet.setores(ativo)
WHERE ativo = TRUE;

\echo '>> Indices criados'

-- ============================================================================
-- PASSO 4: CRIAR FUNCTIONS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 4.1 Function: merge_departamentos (para ETL)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION solpet.merge_departamentos(
  p_id BIGINT,
  p_codigo_interno TEXT,
  p_descricao TEXT,
  p_nivel INTEGER,
  p_parent_id BIGINT
)
RETURNS VOID AS $$
BEGIN
  INSERT INTO solpet.staging_departamentos (id, codigo_interno, descricao, nivel, parent_id, processado, data_importacao)
  VALUES (p_id, p_codigo_interno, p_descricao, p_nivel, p_parent_id, FALSE, NOW())
  ON CONFLICT (id) DO UPDATE SET
    codigo_interno = EXCLUDED.codigo_interno,
    descricao = EXCLUDED.descricao,
    nivel = EXCLUDED.nivel,
    parent_id = EXCLUDED.parent_id,
    processado = FALSE,
    data_importacao = NOW();
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 4.2 Function: merge_produtos (para ETL)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION solpet.merge_produtos(
  p_id BIGINT,
  p_codigo TEXT,
  p_descricao TEXT,
  p_departamento_id BIGINT,
  p_unidade TEXT,
  p_preco_venda NUMERIC,
  p_custo NUMERIC,
  p_ativo BOOLEAN
)
RETURNS VOID AS $$
BEGIN
  INSERT INTO solpet.staging_produtos (id, codigo, descricao, departamento_id, unidade, preco_venda, custo, ativo, processado, data_importacao)
  VALUES (p_id, p_codigo, p_descricao, p_departamento_id, p_unidade, p_preco_venda, p_custo, p_ativo, FALSE, NOW())
  ON CONFLICT (id) DO UPDATE SET
    codigo = EXCLUDED.codigo,
    descricao = EXCLUDED.descricao,
    departamento_id = EXCLUDED.departamento_id,
    unidade = EXCLUDED.unidade,
    preco_venda = EXCLUDED.preco_venda,
    custo = EXCLUDED.custo,
    ativo = EXCLUDED.ativo,
    processado = FALSE,
    data_importacao = NOW();
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 4.3 Function: truncate_table (para limpeza de dados)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION solpet.truncate_table(p_table_name TEXT)
RETURNS VOID AS $$
BEGIN
  EXECUTE format('TRUNCATE TABLE solpet.%I RESTART IDENTITY CASCADE', p_table_name);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

\echo '>> Functions criadas'

-- ============================================================================
-- PASSO 5: CRIAR TRIGGERS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 5.1 Function para atualizar updated_at
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION solpet.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 5.2 Triggers de updated_at
-- ----------------------------------------------------------------------------
CREATE TRIGGER handle_updated_at_metas_mensais
  BEFORE UPDATE ON solpet.metas_mensais
  FOR EACH ROW
  EXECUTE FUNCTION solpet.handle_updated_at();

CREATE TRIGGER handle_updated_at_metas_setor
  BEFORE UPDATE ON solpet.metas_setor
  FOR EACH ROW
  EXECUTE FUNCTION solpet.handle_updated_at();

CREATE TRIGGER handle_updated_at_setores
  BEFORE UPDATE ON solpet.setores
  FOR EACH ROW
  EXECUTE FUNCTION solpet.handle_updated_at();

\echo '>> Triggers criados'

-- ============================================================================
-- PASSO 6: CONFIGURAR PERMISSOES
-- ============================================================================

-- 6.1 Permissao no schema
GRANT USAGE ON SCHEMA solpet TO anon, authenticated, service_role;

-- 6.2 Permissoes em tabelas
GRANT SELECT ON ALL TABLES IN SCHEMA solpet TO anon, authenticated, service_role;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA solpet TO authenticated, service_role;

-- 6.3 Permissoes em sequences
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA solpet TO anon, authenticated, service_role;

-- 6.4 Permissoes em functions
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA solpet TO authenticated, service_role;

-- 6.5 Permissoes futuras (para novas tabelas)
ALTER DEFAULT PRIVILEGES IN SCHEMA solpet
GRANT SELECT ON TABLES TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA solpet
GRANT INSERT, UPDATE, DELETE ON TABLES TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA solpet
GRANT USAGE, SELECT ON SEQUENCES TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA solpet
GRANT EXECUTE ON FUNCTIONS TO authenticated, service_role;

\echo '>> Permissoes configuradas'

-- ============================================================================
-- PASSO 7: CONFIGURAR AUTOVACUUM
-- ============================================================================

-- Tabela vendas (alto volume)
ALTER TABLE solpet.vendas SET (
  autovacuum_vacuum_scale_factor = 0.05,
  autovacuum_analyze_scale_factor = 0.02
);

-- Tabela metas_setor (atualizacoes frequentes)
ALTER TABLE solpet.metas_setor SET (
  autovacuum_vacuum_scale_factor = 0.1,
  autovacuum_analyze_scale_factor = 0.05
);

-- Tabela metas_mensais (atualizacoes frequentes)
ALTER TABLE solpet.metas_mensais SET (
  autovacuum_vacuum_scale_factor = 0.1,
  autovacuum_analyze_scale_factor = 0.05
);

-- Tabela vendas_diarias_por_filial (agregacao diaria)
ALTER TABLE solpet.vendas_diarias_por_filial SET (
  autovacuum_vacuum_scale_factor = 0.1,
  autovacuum_analyze_scale_factor = 0.05
);

\echo '>> Autovacuum configurado'

-- ============================================================================
-- PASSO 8: REGISTRAR TENANT
-- ============================================================================

INSERT INTO public.tenants (name, supabase_schema, created_at)
VALUES ('solpet', 'solpet', NOW())
ON CONFLICT (supabase_schema) DO UPDATE
SET name = EXCLUDED.name, updated_at = NOW();

\echo '>> Tenant registrado em public.tenants'

-- ============================================================================
-- PASSO 9: EXECUTAR ANALYZE
-- ============================================================================

ANALYZE solpet.vendas;
ANALYZE solpet.produtos;
ANALYZE solpet.setores;
ANALYZE solpet.metas_setor;
ANALYZE solpet.metas_mensais;
ANALYZE solpet.departments_level_1;
ANALYZE solpet.departments_level_2;
ANALYZE solpet.departments_level_3;
ANALYZE solpet.despesas;
ANALYZE solpet.descontos_venda;
ANALYZE solpet.perdas;
ANALYZE solpet.faturamento;
ANALYZE solpet.vendas_diarias_por_filial;
ANALYZE solpet.vendas_por_departamento;

\echo '>> ANALYZE executado'

-- ============================================================================
-- PASSO 10: COPIAR DADOS DE REFERENCIA (OPCIONAL)
-- ============================================================================
-- Descomente e execute separadamente se quiser copiar dados do schema origem

/*
-- Copiar hierarquia de departamentos (na ordem correta - do nivel mais alto para o mais baixo)
INSERT INTO solpet.departments_level_6 SELECT * FROM okilao.departments_level_6;
INSERT INTO solpet.departments_level_5 SELECT * FROM okilao.departments_level_5;
INSERT INTO solpet.departments_level_4 SELECT * FROM okilao.departments_level_4;
INSERT INTO solpet.departments_level_3 SELECT * FROM okilao.departments_level_3;
INSERT INTO solpet.departments_level_2 SELECT * FROM okilao.departments_level_2;
INSERT INTO solpet.departments_level_1 SELECT * FROM okilao.departments_level_1;

-- Copiar departamentos_nivel1 (para hierarquia de despesas)
INSERT INTO solpet.departamentos_nivel1 SELECT * FROM okilao.departamentos_nivel1 ON CONFLICT DO NOTHING;

-- Copiar tipos_despesa
INSERT INTO solpet.tipos_despesa SELECT * FROM okilao.tipos_despesa ON CONFLICT DO NOTHING;

-- Copiar motivos_perda
INSERT INTO solpet.motivos_perda SELECT * FROM okilao.motivos_perda ON CONFLICT DO NOTHING;

-- Copiar setores
INSERT INTO solpet.setores (nome, nivel, departamento_ids, ativo, created_at, updated_at)
SELECT nome, nivel, departamento_ids, ativo, created_at, updated_at
FROM okilao.setores;

-- Copiar produtos (depois dos departamentos)
INSERT INTO solpet.produtos SELECT * FROM okilao.produtos ON CONFLICT DO NOTHING;

-- Inicializar controle ETL
INSERT INTO solpet.etl_controle (tabela, status) VALUES
  ('vendas', 'pendente'),
  ('despesas', 'pendente'),
  ('descontos_venda', 'pendente'),
  ('perdas', 'pendente'),
  ('faturamento', 'pendente'),
  ('entradas', 'pendente');
*/

\echo ''
\echo '=============================================='
\echo '>> CLONAGEM CONCLUIDA!'
\echo '=============================================='
\echo ''
\echo 'PROXIMOS PASSOS MANUAIS:'
\echo ''
\echo '1. Adicione "solpet" aos "Exposed schemas" no Supabase:'
\echo '   Dashboard -> Settings -> API -> Exposed schemas'
\echo ''
\echo '2. Importe os dados do novo cliente:'
\echo '   - Hierarquia de departamentos'
\echo '   - Produtos'
\echo '   - Vendas, despesas, etc.'
\echo ''
\echo '3. Crie usuarios para o tenant em public.user_profiles'
\echo ''
\echo '4. Teste o acesso via aplicacao'
\echo ''
\echo '5. Execute as RPC functions necessarias'
\echo '   (get_venda_curva_report, get_ruptura_abcd_report, etc.)'
\echo ''

-- ============================================================================
-- RESUMO DE ESTRUTURA CRIADA
-- ============================================================================
--
-- TABELAS (24):
--   - departamentos_nivel1, departments, departments_level_1-6
--   - descontos_venda, despesas, despesas_diarias_por_filial
--   - entradas, etl_controle, etl_execucoes, faturamento
--   - metas_mensais, metas_setor, motivos_perda, perdas, produtos
--   - setores, staging_departamentos, staging_produtos, tipos_despesa
--   - vendas, vendas_diarias_por_filial, vendas_por_departamento, vendas_produto_mes
--
-- INDICES (50+):
--   - Covering indexes para performance
--   - Partial indexes para queries filtradas
--   - Composite indexes para relatorios
--
-- FUNCTIONS (4):
--   - merge_departamentos, merge_produtos, truncate_table, handle_updated_at
--
-- TRIGGERS (3):
--   - updated_at em metas_mensais, metas_setor, setores
--
-- ============================================================================
